cdef extern from "CsTypes.h":
    pass

cdef extern from "CsDefines.h": 
    unsigned long _CS_MODE_SINGLE "CS_MODE_SINGLE"
    unsigned long _CS_MODE_DUAL "CS_MODE_DUAL"
    unsigned long _CS_MODE_QUAD "CS_MODE_QUAD"
    unsigned long _CS_MODE_OCT "CS_MODE_OCT"
    unsigned long _CS_MASKED_MODE "CS_MASKED_MODE"
    unsigned long _CS_MODE_EXPERT_HISTOGRAM "CS_MODE_EXPERT_HISTOGRAM"
    unsigned long _CS_MODE_SINGLE_CHANNEL2 "CS_MODE_SINGLE_CHANNEL2"
    unsigned long _CS_MODE_POWER_ON "CS_MODE_POWER_ON"
    unsigned long _CS_MODE_REFERENCE_CLK "CS_MODE_REFERENCE_CLK"
    unsigned long _TIMESTAMP_GCLK "TIMESTAMP_GCLK"
    unsigned long _TIMESTAMP_MCLK "TIMESTAMP_MCLK"
    unsigned long _TIMESTAMP_SEG_RESET "TIMESTAMP_SEG_RESET"
    unsigned long _TIMESTAMP_FREERUN "TIMESTAMP_FREERUN"
    unsigned long _TIMESTAMP_DEFAULT "TIMESTAMP_DEFAULT"  
    unsigned long _TxMODE_SLAVE "TxMODE_SLAVE"
    unsigned long _TxMODE_DATA_ANALOGONLY "TxMODE_DATA_ANALOGONLY"
    unsigned long _TxMODE_DATA_FLOAT "TxMODE_DATA_FLOAT"
    unsigned long _TxMODE_TIMESTAMP "TxMODE_TIMESTAMP"
    unsigned long _TxMODE_DATA_16 "TxMODE_DATA_16"
    unsigned long _TxMODE_DATA_ONLYDIGITAL "TxMODE_DATA_ONLYDIGITAL"
    unsigned long _TxMODE_DATA_32 "TxMODE_DATA_32"
    unsigned long _TxMODE_DATA_FFT "TxMODE_DATA_FFT"
    unsigned long _TxMODE_DATA_INTERLEAVED "TxMODE_DATA_INTERLEAVED"
    unsigned long _TxMODE_SEGMENT_TAIL "TxMODE_SEGMENT_TAIL"
    unsigned long _TxMODE_HISTOGRAM "TxMODE_HISTOGRAM"
    unsigned long _TxMODE_DATA_64 "TxMODE_DATA_64"
    unsigned long _CS_CHAN_1 "CS_CHAN_1" 
    unsigned long _CS_CHAN_2 "CS_CHAN_2" 
    unsigned long _CS_FILTER_OFF "CS_FILTER_OFF" 
    unsigned long _CS_FILTER_ON "CS_FILTER_ON"  
    unsigned long _CS_COUPLING_DC "CS_COUPLING_DC"        
    unsigned long _CS_COUPLING_AC "CS_COUPLING_AC"        
    unsigned long _CS_COUPLING_MASK "CS_COUPLING_MASK"      
    unsigned long _CS_DIFFERENTIAL_INPUT "CS_DIFFERENTIAL_INPUT"
    unsigned long _CS_DIRECT_ADC_INPUT "CS_DIRECT_ADC_INPUT"   
    unsigned long _CS_REAL_IMP_1M_OHM "CS_REAL_IMP_1M_OHM"
    unsigned long _CS_REAL_IMP_50_OHM "CS_REAL_IMP_50_OHM" 
    unsigned long _CS_REAL_IMP_1K_OHM "CS_REAL_IMP_1K_OHM" 
    unsigned long _CS_GAIN_100_V "CS_GAIN_100_V"
    unsigned long _CS_GAIN_40_V "CS_GAIN_40_V"
    unsigned long _CS_GAIN_20_V "CS_GAIN_20_V"
    unsigned long _CS_GAIN_10_V "CS_GAIN_10_V"
    unsigned long _CS_GAIN_5_V "CS_GAIN_5_V"
    unsigned long _CS_GAIN_8_V "CS_GAIN_8_V"
    unsigned long _CS_GAIN_4_V "CS_GAIN_4_V"
    unsigned long _CS_GAIN_3_V "CS_GAIN_3_V"
    unsigned long _CS_GAIN_2_V "CS_GAIN_2_V"
    unsigned long _CS_GAIN_1_V "CS_GAIN_1_V"
    unsigned long _CS_GAIN_800_MV "CS_GAIN_800_MV"
    unsigned long _CS_GAIN_500_MV "CS_GAIN_500_MV"
    unsigned long _CS_GAIN_400_MV "CS_GAIN_400_MV"
    unsigned long _CS_GAIN_200_MV "CS_GAIN_200_MV"
    unsigned long _CS_GAIN_100_MV "CS_GAIN_100_MV"
    unsigned long _CS_GAIN_50_MV "CS_GAIN_50_MV"
    unsigned long _CS_TRIG_COND_NEG_SLOPE "CS_TRIG_COND_NEG_SLOPE"
    unsigned long _CS_TRIG_COND_POS_SLOPE "CS_TRIG_COND_POS_SLOPE"
    unsigned long _CS_TRIG_COND_PULSE_WIDTH "CS_TRIG_COND_PULSE_WIDTH" 
    unsigned long _CS_MAX_TRIG_COND "CS_MAX_TRIG_COND"         
    unsigned long _CS_RELATION_OR "CS_RELATION_OR"
    unsigned long _CS_RELATION_AND "CS_RELATION_AND"
    unsigned long _CS_TRIG_ENGINES_DIS "CS_TRIG_ENGINES_DIS"
    unsigned long _CS_TRIG_ENGINES_EN "CS_TRIG_ENGINES_EN"
    unsigned long _CS_TRIG_SOURCE_DISABLE "CS_TRIG_SOURCE_DISABLE"
    unsigned long _CS_TRIG_SOURCE_CHAN_1 "CS_TRIG_SOURCE_CHAN_1"
    unsigned long _CS_TRIG_SOURCE_CHAN_2 "CS_TRIG_SOURCE_CHAN_2"
    unsigned long _CS_TRIG_SOURCE_EXT "CS_TRIG_SOURCE_EXT"
    unsigned long _CS_BOARD_INFO "CS_BOARD_INFO"
    unsigned long _CS_SYSTEM "CS_SYSTEM"
    unsigned long _CS_CHANNEL "CS_CHANNEL"
    unsigned long _CS_TRIGGER "CS_TRIGGER"
    unsigned long _CS_ACQUISITION "CS_ACQUISITION"
    unsigned long _CS_PARAMS "CS_PARAMS"
    unsigned long _CS_FIR_CONFIG "CS_FIR_CONFIG"
    unsigned long _CS_EXTENDED_BOARD_OPTIONS "CS_EXTENDED_BOARD_OPTIONS"
    unsigned long _CS_TIMESTAMP_TICKFREQUENCY "CS_TIMESTAMP_TICKFREQUENCY"
    unsigned long _CS_CHANNEL_ARRAY "CS_CHANNEL_ARRAY"
    unsigned long _CS_TRIGGER_ARRAY "CS_TRIGGER_ARRAY"
    unsigned long _CS_SMT_ENVELOPE_CONFIG "CS_SMT_ENVELOPE_CONFIG"
    unsigned long _CS_SMT_HISTOGRAM_CONFIG "CS_SMT_HISTOGRAM_CONFIG"
    unsigned long _CS_FFT_CONFIG "CS_FFT_CONFIG"
    unsigned long _CS_FFTWINDOW_CONFIG "CS_FFTWINDOW_CONFIG"
    unsigned long _CS_MULREC_AVG_COUNT "CS_MULREC_AVG_COUNT"
    unsigned long _CS_TRIG_OUT_CFG "CS_TRIG_OUT_CFG"
    unsigned long _CS_GET_SEGMENT_COUNT "CS_GET_SEGMENT_COUNT"
    unsigned long _CS_TRIGGERED_INFO "CS_TRIGGERED_INFO"
    unsigned long _CS_SEGMENTTAIL_SIZE_BYTES "CS_SEGMENTTAIL_SIZE_BYTES"
    unsigned long _CS_STREAM_SEGMENTDATA_SIZE_SAMPLES "CS_STREAM_SEGMENTDATA_SIZE_SAMPLES"
    unsigned long _CS_STREAM_TOTALDATA_SIZE_BYTES "CS_STREAM_TOTALDATA_SIZE_BYTES"
    unsigned long _CS_IDENTIFY_LED "CS_IDENTIFY_LED"
    unsigned long _CS_CAPTURE_MODE "CS_CAPTURE_MODE" 
    unsigned long _CS_DATAPACKING_MODE "CS_DATAPACKING_MODE" 
    unsigned long _CS_GET_DATAFORMAT_INFO "CS_GET_DATAFORMAT_INFO"
    unsigned long _CS_CURRENT_CONFIGURATION "CS_CURRENT_CONFIGURATION"
    unsigned long _CS_ACQUISITION_CONFIGURATION "CS_ACQUISITION_CONFIGURATION"
    unsigned long _CS_ACQUIRED_CONFIGURATION "CS_ACQUIRED_CONFIGURATION"
    unsigned long _ACTION_COMMIT "ACTION_COMMIT" 
    unsigned long _ACTION_START "ACTION_START"
    unsigned long _ACTION_FORCE "ACTION_FORCE"
    unsigned long _ACTION_ABORT "ACTION_ABORT"
    unsigned long _ACTION_CALIB "ACTION_CALIB"
    unsigned long _ACTION_RESET "ACTION_RESET"
    unsigned long _ACTION_COMMIT_COERCE "ACTION_COMMIT_COERCE" 
    unsigned long _ACTION_TIMESTAMP_RESET "ACTION_TIMESTAMP_RESET"
    unsigned long _ACTION_HISTOGRAM_RESET "ACTION_HISTOGRAM_RESET"
    unsigned long _ACTION_ENCODER1_COUNT_RESET "ACTION_ENCODER1_COUNT_RESET"
    unsigned long _ACTION_ENCODER2_COUNT_RESET "ACTION_ENCODER2_COUNT_RESET" 
    unsigned long _ACTION_HARD_RESET "ACTION_HARD_RESET" 
    unsigned long _ACQ_STATUS_READY "ACQ_STATUS_READY"
    unsigned long _ACQ_STATUS_WAIT_TRIGGER "ACQ_STATUS_WAIT_TRIGGER"
    unsigned long _ACQ_STATUS_TRIGGERED "ACQ_STATUS_TRIGGERED"
    unsigned long _ACQ_STATUS_BUSY_TX "ACQ_STATUS_BUSY_TX"
    unsigned long _ACQ_STATUS_BUSY_CALIB "ACQ_STATUS_BUSY_CALIB"
    unsigned long _CSDEMO8_BOARDTYPE "CSDEMO8_BOARDTYPE"
    unsigned long _CSDEMO12_BOARDTYPE "CSDEMO12_BOARDTYPE"
    unsigned long _CSDEMO14_BOARDTYPE "CSDEMO14_BOARDTYPE"
    unsigned long _CSDEMO16_BOARDTYPE "CSDEMO16_BOARDTYPE"
    unsigned long _CSDEMO32_BOARDTYPE "CSDEMO32_BOARDTYPE"
    unsigned long _CSDEMO_BT_MASK "CSDEMO_BT_MASK"     
    unsigned long _CSDEMO_BT_FIRST_BOARD "CSDEMO_BT_FIRST_BOARD" 
    unsigned long _CSDEMO_BT_LAST_BOARD "CSDEMO_BT_LAST_BOARD" 
    unsigned long _CSPCIEx_BOARDTYPE "CSPCIEx_BOARDTYPE"       
    unsigned long _CSNUCLEONBASE_BOARDTYPE "CSNUCLEONBASE_BOARDTYPE" 
    unsigned long _CS16x1_BOARDTYPE "CS16x1_BOARDTYPE" 
    unsigned long _CS16x2_BOARDTYPE "CS16x2_BOARDTYPE" 
    unsigned long _CS14x1_BOARDTYPE "CS14x1_BOARDTYPE" 
    unsigned long _CS14x2_BOARDTYPE "CS14x2_BOARDTYPE" 
    unsigned long _CS12x1_BOARDTYPE "CS12x1_BOARDTYPE" 
    unsigned long _CS12x2_BOARDTYPE "CS12x2_BOARDTYPE" 
    unsigned long _CS16xyy_BT_FIRST_BOARD "CS16xyy_BT_FIRST_BOARD" 
    unsigned long _CS16xyy_LAST_BOARD "CS16xyy_LAST_BOARD"     
    unsigned long _CS16xyy_BASEBOARD "CS16xyy_BASEBOARD"      
    unsigned long _CSE42x0_BOARDTYPE "CSE42x0_BOARDTYPE"  
    unsigned long _CSE42x2_BOARDTYPE "CSE42x2_BOARDTYPE"  
    unsigned long _CSE42x4_BOARDTYPE "CSE42x4_BOARDTYPE"  
    unsigned long _CSE42x7_BOARDTYPE "CSE42x7_BOARDTYPE"  
    unsigned long _CSE43x0_BOARDTYPE "CSE43x0_BOARDTYPE"  
    unsigned long _CSE43x2_BOARDTYPE "CSE43x2_BOARDTYPE"  
    unsigned long _CSE43x4_BOARDTYPE "CSE43x4_BOARDTYPE"  
    unsigned long _CSE43x7_BOARDTYPE "CSE43x7_BOARDTYPE"  
    unsigned long _CSE44x0_BOARDTYPE "CSE44x0_BOARDTYPE"  
    unsigned long _CSE44x2_BOARDTYPE "CSE44x2_BOARDTYPE"  
    unsigned long _CSE44x4_BOARDTYPE "CSE44x4_BOARDTYPE"  
    unsigned long _CSE44x7_BOARDTYPE "CSE44x7_BOARDTYPE"  
    unsigned long _CSE4abc_FIRST_BOARD "CSE4abc_FIRST_BOARD" 
    unsigned long _CSE4abc_LAST_BOARD "CSE4abc_LAST_BOARD"  
    unsigned long _CSE4abc_BASEBOARD "CSE4abc_BASEBOARD"   
    unsigned long _CS8220_BOARDTYPE "CS8220_BOARDTYPE" 
    unsigned long _CS8221_BOARDTYPE "CS8221_BOARDTYPE" 
    unsigned long _CS8222_BOARDTYPE "CS8222_BOARDTYPE" 
    unsigned long _CS8223_BOARDTYPE "CS8223_BOARDTYPE" 
    unsigned long _CS8224_BOARDTYPE "CS8224_BOARDTYPE" 
    unsigned long _CS8225_BOARDTYPE "CS8225_BOARDTYPE" 
    unsigned long _CS8226_BOARDTYPE "CS8226_BOARDTYPE" 
    unsigned long _CS8227_BOARDTYPE "CS8227_BOARDTYPE" 
    unsigned long _CS8228_BOARDTYPE "CS8228_BOARDTYPE" 
    unsigned long _CS8229_BOARDTYPE "CS8229_BOARDTYPE" 
    unsigned long _CS822x_BOARDTYPE_MASK "CS822x_BOARDTYPE_MASK"
    unsigned long _CS8240_BOARDTYPE "CS8240_BOARDTYPE" 
    unsigned long _CS8241_BOARDTYPE "CS8241_BOARDTYPE" 
    unsigned long _CS8242_BOARDTYPE "CS8242_BOARDTYPE" 
    unsigned long _CS8243_BOARDTYPE "CS8243_BOARDTYPE" 
    unsigned long _CS8244_BOARDTYPE "CS8244_BOARDTYPE" 
    unsigned long _CS8245_BOARDTYPE "CS8245_BOARDTYPE" 
    unsigned long _CS8246_BOARDTYPE "CS8246_BOARDTYPE" 
    unsigned long _CS8247_BOARDTYPE "CS8247_BOARDTYPE" 
    unsigned long _CS8248_BOARDTYPE "CS8248_BOARDTYPE" 
    unsigned long _CS8249_BOARDTYPE "CS8249_BOARDTYPE" 
    unsigned long _CS824x_BOARDTYPE_MASK "CS824x_BOARDTYPE_MASK"
    unsigned long _CS8280_BOARDTYPE "CS8280_BOARDTYPE" 
    unsigned long _CS8281_BOARDTYPE "CS8281_BOARDTYPE" 
    unsigned long _CS8282_BOARDTYPE "CS8282_BOARDTYPE" 
    unsigned long _CS8283_BOARDTYPE "CS8283_BOARDTYPE" 
    unsigned long _CS8284_BOARDTYPE "CS8284_BOARDTYPE" 
    unsigned long _CS8285_BOARDTYPE "CS8285_BOARDTYPE" 
    unsigned long _CS8286_BOARDTYPE "CS8286_BOARDTYPE" 
    unsigned long _CS8287_BOARDTYPE "CS8287_BOARDTYPE" 
    unsigned long _CS8288_BOARDTYPE "CS8288_BOARDTYPE" 
    unsigned long _CS8289_BOARDTYPE "CS8289_BOARDTYPE" 
    unsigned long _CS828x_BOARDTYPE_MASK "CS828x_BOARDTYPE_MASK"
    unsigned long _CS8320_BOARDTYPE "CS8320_BOARDTYPE" 
    unsigned long _CS8321_BOARDTYPE "CS8321_BOARDTYPE" 
    unsigned long _CS8322_BOARDTYPE "CS8322_BOARDTYPE" 
    unsigned long _CS8323_BOARDTYPE "CS8323_BOARDTYPE" 
    unsigned long _CS8324_BOARDTYPE "CS8324_BOARDTYPE" 
    unsigned long _CS8325_BOARDTYPE "CS8325_BOARDTYPE" 
    unsigned long _CS8326_BOARDTYPE "CS8326_BOARDTYPE" 
    unsigned long _CS8327_BOARDTYPE "CS8327_BOARDTYPE" 
    unsigned long _CS8328_BOARDTYPE "CS8328_BOARDTYPE" 
    unsigned long _CS8329_BOARDTYPE "CS8329_BOARDTYPE" 
    unsigned long _CS832x_BOARDTYPE_MASK "CS832x_BOARDTYPE_MASK" 
    unsigned long _CS8340_BOARDTYPE "CS8340_BOARDTYPE" 
    unsigned long _CS8341_BOARDTYPE "CS8341_BOARDTYPE" 
    unsigned long _CS8342_BOARDTYPE "CS8342_BOARDTYPE" 
    unsigned long _CS8343_BOARDTYPE "CS8343_BOARDTYPE" 
    unsigned long _CS8344_BOARDTYPE "CS8344_BOARDTYPE" 
    unsigned long _CS8345_BOARDTYPE "CS8345_BOARDTYPE" 
    unsigned long _CS8346_BOARDTYPE "CS8346_BOARDTYPE" 
    unsigned long _CS8347_BOARDTYPE "CS8347_BOARDTYPE" 
    unsigned long _CS8348_BOARDTYPE "CS8348_BOARDTYPE" 
    unsigned long _CS8349_BOARDTYPE "CS8349_BOARDTYPE" 
    unsigned long _CS834x_BOARDTYPE_MASK "CS834x_BOARDTYPE_MASK" 
    unsigned long _CS8380_BOARDTYPE "CS8380_BOARDTYPE" 
    unsigned long _CS8381_BOARDTYPE "CS8381_BOARDTYPE" 
    unsigned long _CS8382_BOARDTYPE "CS8382_BOARDTYPE" 
    unsigned long _CS8383_BOARDTYPE "CS8383_BOARDTYPE" 
    unsigned long _CS8384_BOARDTYPE "CS8384_BOARDTYPE" 
    unsigned long _CS8385_BOARDTYPE "CS8385_BOARDTYPE" 
    unsigned long _CS8386_BOARDTYPE "CS8386_BOARDTYPE" 
    unsigned long _CS8387_BOARDTYPE "CS8387_BOARDTYPE" 
    unsigned long _CS8388_BOARDTYPE "CS8388_BOARDTYPE" 
    unsigned long _CS8389_BOARDTYPE "CS8389_BOARDTYPE"
    unsigned long _CS838x_BOARDTYPE_MASK "CS838x_BOARDTYPE_MASK" 
    unsigned long _CS8210_BOARDTYPE "CS8210_BOARDTYPE" 
    unsigned long _CS8211_BOARDTYPE "CS8211_BOARDTYPE" 
    unsigned long _CS8212_BOARDTYPE "CS8212_BOARDTYPE" 
    unsigned long _CS8213_BOARDTYPE "CS8213_BOARDTYPE" 
    unsigned long _CS8214_BOARDTYPE "CS8214_BOARDTYPE" 
    unsigned long _CS8215_BOARDTYPE "CS8215_BOARDTYPE" 
    unsigned long _CS8216_BOARDTYPE "CS8216_BOARDTYPE" 
    unsigned long _CS8217_BOARDTYPE "CS8217_BOARDTYPE" 
    unsigned long _CS8218_BOARDTYPE "CS8218_BOARDTYPE" 
    unsigned long _CS8219_BOARDTYPE "CS8219_BOARDTYPE" 
    unsigned long _CS821x_BOARDTYPE_MASK "CS821x_BOARDTYPE_MASK" 
    unsigned long _CS8310_BOARDTYPE "CS8310_BOARDTYPE" 
    unsigned long _CS8311_BOARDTYPE "CS8311_BOARDTYPE" 
    unsigned long _CS8312_BOARDTYPE "CS8312_BOARDTYPE" 
    unsigned long _CS8313_BOARDTYPE "CS8313_BOARDTYPE" 
    unsigned long _CS8314_BOARDTYPE "CS8314_BOARDTYPE" 
    unsigned long _CS8315_BOARDTYPE "CS8315_BOARDTYPE" 
    unsigned long _CS8316_BOARDTYPE "CS8316_BOARDTYPE" 
    unsigned long _CS8317_BOARDTYPE "CS8317_BOARDTYPE" 
    unsigned long _CS8318_BOARDTYPE "CS8318_BOARDTYPE" 
    unsigned long _CS8319_BOARDTYPE "CS8319_BOARDTYPE" 
    unsigned long _CS831x_BOARDTYPE_MASK "CS831x_BOARDTYPE_MASK" 
    unsigned long _CS8410_BOARDTYPE "CS8410_BOARDTYPE" 
    unsigned long _CS8412_BOARDTYPE "CS8412_BOARDTYPE" 
    unsigned long _CS8420_BOARDTYPE "CS8420_BOARDTYPE" 
    unsigned long _CS8422_BOARDTYPE "CS8422_BOARDTYPE" 
    unsigned long _CS8440_BOARDTYPE "CS8440_BOARDTYPE" 
    unsigned long _CS8442_BOARDTYPE "CS8442_BOARDTYPE" 
    unsigned long _CS8480_BOARDTYPE "CS8480_BOARDTYPE" 
    unsigned long _CS8482_BOARDTYPE "CS8482_BOARDTYPE" 
    unsigned long _CS84xx_BOARDTYPE_MASK "CS84xx_BOARDTYPE_MASK" 
    unsigned long _CS8_BT_MASK "CS8_BT_MASK"        
    unsigned long _CS8_BT_FIRST_BOARD "CS8_BT_FIRST_BOARD" 
    unsigned long _CS8_BT_LAST_BOARD "CS8_BT_LAST_BOARD"  
    unsigned long _CS8xxx_BASEBOARD "CS8xxx_BASEBOARD"   
    unsigned long _CS_ZAP_FIRST_BOARD "CS_ZAP_FIRST_BOARD" 
    unsigned long _CS_ZAP_LAST_BOARD "CS_ZAP_LAST_BOARD"  
    unsigned long _CS_ZAP_BASEBOARD "CS_ZAP_BASEBOARD"   
    unsigned long _CS22G8_BOARDTYPE "CS22G8_BOARDTYPE"      
    unsigned long _CSxyG8_BOARDTYPE_MASK "CSxyG8_BOARDTYPE_MASK" 
    unsigned long _CS21G8_BOARDTYPE "CS21G8_BOARDTYPE"      
    unsigned long _CS11G8_BOARDTYPE "CS11G8_BOARDTYPE"      
    unsigned long _LAB11G_BOARDTYPE "LAB11G_BOARDTYPE"      
    unsigned long _CSxyG8_FIRST_BOARD "CSxyG8_FIRST_BOARD"    
    unsigned long _CSxyG8_LAST_BOARD "CSxyG8_LAST_BOARD"  
    unsigned long _CS_BASE8_BOARDTYPE "CS_BASE8_BOARDTYPE" 
    unsigned long _CS_COBRAX_BOARDTYPE_MASK "CS_COBRAX_BOARDTYPE_MASK" 
    unsigned long _CSX11G8_BOARDTYPE "CSX11G8_BOARDTYPE" 
    unsigned long _CSX21G8_BOARDTYPE "CSX21G8_BOARDTYPE" 
    unsigned long _CSX22G8_BOARDTYPE "CSX22G8_BOARDTYPE" 
    unsigned long _CSX13G8_BOARDTYPE "CSX13G8_BOARDTYPE" 
    unsigned long _CSX23G8_BOARDTYPE "CSX23G8_BOARDTYPE" 
    unsigned long _CSX14G8_BOARDTYPE "CSX14G8_BOARDTYPE" 
    unsigned long _CSX_NTS_BOARDTYPE "CSX_NTS_BOARDTYPE" 
    unsigned long _CSX24G8_BOARDTYPE "CSX24G8_BOARDTYPE" 
    unsigned long _CSEcdG8_FIRST_BOARD "CSEcdG8_FIRST_BOARD"	
    unsigned long _CSEcdG8_LAST_BOARD "CSEcdG8_LAST_BOARD"	
    unsigned long _CS12500_BOARDTYPE "CS12500_BOARDTYPE" 
    unsigned long _CS121G_BOARDTYPE "CS121G_BOARDTYPE"  
    unsigned long _CS122G_BOARDTYPE "CS122G_BOARDTYPE"  
    unsigned long _CS14250_BOARDTYPE "CS14250_BOARDTYPE" 
    unsigned long _CS14500_BOARDTYPE "CS14500_BOARDTYPE" 
    unsigned long _CS141G_BOARDTYPE "CS141G_BOARDTYPE"  
    unsigned long _CSJD_FIRST_BOARD "CSJD_FIRST_BOARD"  
    unsigned long _CSJD_LAST_BOARD "CSJD_LAST_BOARD"   
    unsigned long _CSUSB_BOARDTYPE "CSUSB_BOARDTYPE"      
    unsigned long _CSUSB_BT_FIRST_BOARD "CSUSB_BT_FIRST_BOARD" 
    unsigned long _CSUSB_BT_LAST_BOARD "CSUSB_BT_LAST_BOARD"  
    unsigned long _CSDECADE123G_BOARDTYPE "CSDECADE123G_BOARDTYPE" 
    unsigned long _CSDECADE126G_BOARDTYPE "CSDECADE126G_BOARDTYPE" 
    unsigned long _CSDECADE_FIRST_BOARD "CSDECADE_FIRST_BOARD"   
    unsigned long _CSDECADE_LAST_BOARD "CSDECADE_LAST_BOARD"    
    unsigned long _CSHEXAGON_161G4_BOARDTYPE "CSHEXAGON_161G4_BOARDTYPE" 
    unsigned long _CSHEXAGON_161G2_BOARDTYPE "CSHEXAGON_161G2_BOARDTYPE" 
    unsigned long _CSHEXAGON_16504_BOARDTYPE "CSHEXAGON_16504_BOARDTYPE" 
    unsigned long _CSHEXAGON_16502_BOARDTYPE "CSHEXAGON_16502_BOARDTYPE" 
    unsigned long _CSHEXAGON_FIRST_BOARD "CSHEXAGON_FIRST_BOARD"     
    unsigned long _CSHEXAGON_LAST_BOARD "CSHEXAGON_LAST_BOARD"   
    unsigned long _FCI_BOARDTYPE "FCI_BOARDTYPE" 
    unsigned long _CS_TIMEOUT_DISABLE "CS_TIMEOUT_DISABLE" 
    unsigned long _ACQ_EVENT_TRIGGERED "ACQ_EVENT_TRIGGERED"
    unsigned long _ACQ_EVENT_END_BUSY "ACQ_EVENT_END_BUSY"
    unsigned long _ACQ_EVENT_END_TXFER "ACQ_EVENT_END_TXFER"
    unsigned long _ACQ_EVENT_ALARM "ACQ_EVENT_ALARM"
    unsigned long _NUMBER_ACQ_EVENTS "NUMBER_ACQ_EVENTS"
    unsigned long _CAPS_SAMPLE_RATES "CAPS_SAMPLE_RATES" 
    unsigned long _CAPS_INPUT_RANGES "CAPS_INPUT_RANGES" 
    unsigned long _CAPS_IMPEDANCES "CAPS_IMPEDANCES" 
    unsigned long _CAPS_COUPLINGS "CAPS_COUPLINGS" 
    unsigned long _CAPS_ACQ_MODES "CAPS_ACQ_MODES" 
    unsigned long _CAPS_TERMINATIONS "CAPS_TERMINATIONS" 
    unsigned long _CAPS_FLEXIBLE_TRIGGER "CAPS_FLEXIBLE_TRIGGER" 
    unsigned long _CAPS_BOARD_TRIGGER_ENGINES "CAPS_BOARD_TRIGGER_ENGINES" 
    unsigned long _CAPS_TRIGGER_SOURCES "CAPS_TRIGGER_SOURCES" 
    unsigned long _CAPS_FILTERS "CAPS_FILTERS" 
    unsigned long _CAPS_MAX_SEGMENT_PADDING "CAPS_MAX_SEGMENT_PADDING" 
    unsigned long _CAPS_DC_OFFSET_ADJUST "CAPS_DC_OFFSET_ADJUST" 
    unsigned long _CAPS_CLK_IN "CAPS_CLK_IN" 
    unsigned long _CAPS_BOOTIMAGE0 "CAPS_BOOTIMAGE0" 
    unsigned long _CAPS_AUX_CONFIG "CAPS_AUX_CONFIG" 
    unsigned long _CAPS_CLOCK_OUT "CAPS_CLOCK_OUT"        
    unsigned long _CAPS_TRIG_OUT "CAPS_TRIG_OUT"         
    unsigned long _CAPS_TRIG_ENABLE "CAPS_TRIG_ENABLE"      
    unsigned long _CAPS_AUX_OUT "CAPS_AUX_OUT"          
    unsigned long _CAPS_AUX_IN_TIMESTAMP "CAPS_AUX_IN_TIMESTAMP" 
    unsigned long _CAPS_FWCHANGE_REBOOT "CAPS_FWCHANGE_REBOOT" 
    unsigned long _CAPS_EXT_TRIGGER_UNIPOLAR "CAPS_EXT_TRIGGER_UNIPOLAR" 
    unsigned long _CAPS_TRIG_ENGINES_PER_CHAN "CAPS_TRIG_ENGINES_PER_CHAN" 
    unsigned long _CAPS_MULREC "CAPS_MULREC" 
    unsigned long _CAPS_TRIGGER_RES "CAPS_TRIGGER_RES" 
    unsigned long _CAPS_MIN_EXT_RATE "CAPS_MIN_EXT_RATE" 
    unsigned long _CAPS_SKIP_COUNT "CAPS_SKIP_COUNT" 
    unsigned long _CAPS_MAX_EXT_RATE "CAPS_MAX_EXT_RATE" 
    unsigned long _CAPS_TRANSFER_EX "CAPS_TRANSFER_EX" 
    unsigned long _CAPS_STM_TRANSFER_SIZE_BOUNDARY "CAPS_STM_TRANSFER_SIZE_BOUNDARY" 
    unsigned long _CAPS_STM_MAX_SEGMENTSIZE "CAPS_STM_MAX_SEGMENTSIZE" 
    unsigned long _CAPS_SINGLE_CHANNEL2 "CAPS_SINGLE_CHANNEL2" 
    unsigned long _CAPS_SELF_IDENTIFY "CAPS_SELF_IDENTIFY" 
    unsigned long _CAPS_MAX_PRE_TRIGGER "CAPS_MAX_PRE_TRIGGER" 
    unsigned long _CAPS_DEPTH_INCREMENT "CAPS_DEPTH_INCREMENT" 
    unsigned long _CAPS_TRIGGER_DELAY_INCREMENT "CAPS_TRIGGER_DELAY_INCREMENT" 
    unsigned long _CS_NO_FILTER "CS_NO_FILTER"  
    unsigned long _CS_NO_EXTTRIG "CS_NO_EXTTRIG" 
    unsigned long _CS_MODE_NO_DDC "CS_MODE_NO_DDC"     
    unsigned long _CS_DDC_MODE_ENABLE "CS_DDC_MODE_ENABLE" 
    unsigned long _CS_DDC_MODE_CH1 "CS_DDC_MODE_CH1"    
    unsigned long _CS_DDC_MODE_CH2 "CS_DDC_MODE_CH2"    
    unsigned long _CS_DDC_DEBUG_MUX "CS_DDC_DEBUG_MUX"   
    unsigned long _CS_DDC_DEBUG_NCO "CS_DDC_DEBUG_NCO"   
    unsigned long _CS_DDC_MODE_LAST "CS_DDC_MODE_LAST"   
    unsigned long _CS_DDC_MUX_ENABLE "CS_DDC_MUX_ENABLE" 
    unsigned long _CS_DDC_CORE_CONFIG "CS_DDC_CORE_CONFIG" 
    unsigned long _CS_DDC_FIR_COEF_CONFIG "CS_DDC_FIR_COEF_CONFIG" 
    unsigned long _CS_DDC_CFIR_COEF_CONFIG "CS_DDC_CFIR_COEF_CONFIG" 
    unsigned long _CS_DDC_PFIR_COEF_CONFIG "CS_DDC_PFIR_COEF_CONFIG" 
    unsigned long _CS_DDC_WRITE_FIFO_DATA "CS_DDC_WRITE_FIFO_DATA" 
    unsigned long _CS_DDC_READ_FIFO_DATA "CS_DDC_READ_FIFO_DATA"
    unsigned long _SIZE_OF_FIR_COEFS "SIZE_OF_FIR_COEFS"         
    unsigned long _SIZE_OF_CFIR_COEFS "SIZE_OF_CFIR_COEFS"        
    unsigned long _SIZE_OF_PFIR_COEFS "SIZE_OF_PFIR_COEFS"        
    unsigned long _DDC_FILTER_COEFS_MAX_SIZE "DDC_FILTER_COEFS_MAX_SIZE"
    unsigned long _DDC_CORE_CONFIG_OFFSET "DDC_CORE_CONFIG_OFFSET"    
    unsigned long _CS_DDC_CONFIG "CS_DDC_CONFIG"
    unsigned long _CS_DDC_SEND_CMD "CS_DDC_SEND_CMD"
    unsigned long _CS_DDC_SCALE_OVERFLOW_STATUS "CS_DDC_SCALE_OVERFLOW_STATUS"
    unsigned long _CS_PE_ENABLE "CS_PE_ENABLE"  
    unsigned long _CS_PE_DISABLE "CS_PE_DISABLE" 
    unsigned long _CS_ENCODER1_COUNT_RESET "CS_ENCODER1_COUNT_RESET" 
    unsigned long _CS_ENCODER2_COUNT_RESET "CS_ENCODER2_COUNT_RESET" 
    unsigned long _CS_ENCODER1_CONFIG "CS_ENCODER1_CONFIG" 
    unsigned long _CS_ENCODER2_CONFIG "CS_ENCODER2_CONFIG" 
    unsigned long _CS_ENCODER1_COUNT "CS_ENCODER1_COUNT" 
    unsigned long _CS_ENCODER2_COUNT "CS_ENCODER2_COUNT" 
    unsigned long _CS_PE_INPUT_TYPE_STEPANDDIRECTION "CS_PE_INPUT_TYPE_STEPANDDIRECTION" 
    unsigned long _CS_PE_INPUT_TYPE_QUADRATURE "CS_PE_INPUT_TYPE_QUADRATURE"    
    unsigned long _CS_PE_ENCODER_MODE_STAMP "CS_PE_ENCODER_MODE_STAMP" 
    unsigned long _CS_PE_ENCODER_MODE_TOP "CS_PE_ENCODER_MODE_TOP"   
    unsigned long _CS_OCT_ENABLE "CS_OCT_ENABLE"  
    unsigned long _CS_OCT_DISABLE "CS_OCT_DISABLE" 
    unsigned long _CS_OCT_MODE0 "CS_OCT_MODE0"
    unsigned long _CS_OCT_MODE1 "CS_OCT_MODE1"
    unsigned long _CS_OCT_CORE_CONFIG "CS_OCT_CORE_CONFIG" 
    unsigned long _CS_OCT_RECORD_LEN "CS_OCT_RECORD_LEN"  
    unsigned long _CS_OCT_CMD_MODE "CS_OCT_CMD_MODE"    

cdef extern from "CsExpert.h":
    unsigned long _CS_MODE_USER1 "CS_MODE_USER1"
    unsigned long _CS_MODE_USER2 "CS_MODE_USER2"
    unsigned long _CS_MODE_SW_AVERAGING "CS_MODE_SW_AVERAGING"
    unsigned long _CS_BBOPTIONS_FIR "CS_BBOPTIONS_FIR"
    unsigned long _CS_BBOPTIONS_AVERAGING "CS_BBOPTIONS_AVERAGING"
    unsigned long _CS_BBOPTIONS_MINMAXDETECT "CS_BBOPTIONS_MINMAXDETECT"
    unsigned long _CS_BBOPTIONS_CASCADESTREAM "CS_BBOPTIONS_CASCADESTREAM"
    unsigned long _CS_BBOPTIONS_MULREC_AVG "CS_BBOPTIONS_MULREC_AVG"
    unsigned long _CS_BBOPTIONS_SMT "CS_BBOPTIONS_SMT"
    unsigned long _CS_BBOPTIONS_FFT_8K "CS_BBOPTIONS_FFT_8K"
    unsigned long _CS_BBOPTIONS_FFT_4K "CS_BBOPTIONS_FFT_4K"
    unsigned long _CS_BBOPTIONS_MULREC_AVG_TD "CS_BBOPTIONS_MULREC_AVG_TD"
    unsigned long _CS_BBOPTIONS_DDC "CS_BBOPTIONS_DDC"
    unsigned long _CS_BBOPTIONS_OCT "CS_BBOPTIONS_OCT"
    unsigned long _CS_BBOPTIONS_STREAM "CS_BBOPTIONS_STREAM"
    unsigned long _CS_AOPTIONS_HISTOGRAM "CS_AOPTIONS_HISTOGRAM"
    unsigned long _CS_BBOPTIONS_FFTMASK "CS_BBOPTIONS_FFTMASK"            
    unsigned long _CS_BBOPTIONS_EXPERT_MASK "CS_BBOPTIONS_EXPERT_MASK"
    unsigned long _CSMV_BBOPTIONS_BIG_TRIGGER "CSMV_BBOPTIONS_BIG_TRIGGER"
    unsigned long _MAX_HW_AVERAGING_DEPTH "MAX_HW_AVERAGING_DEPTH"
    unsigned long _MAX_HW_AVERAGE_SEGMENTCOUNT "MAX_HW_AVERAGE_SEGMENTCOUNT"
    unsigned long _MAX_SW_AVERAGING_SEGMENTSIZE "MAX_SW_AVERAGING_SEGMENTSIZE"
    unsigned long _MAX_SW_AVERAGE_SEGMENTCOUNT "MAX_SW_AVERAGE_SEGMENTCOUNT"
    unsigned long _MAX_MINMAXDETECT_SEGMENTSIZE "MAX_MINMAXDETECT_SEGMENTSIZE"
    unsigned long _MAX_MINMAXDETECT_SEGMENTCOUNT "MAX_MINMAXDETECT_SEGMENTCOUNT"
    unsigned long _MAX_DISKSTREAM_CHANNELS "MAX_DISKSTREAM_CHANNELS" 
    unsigned long _EXFN_CREATEMINMAXQUEUE "EXFN_CREATEMINMAXQUEUE"
    unsigned long _EXFN_DESTROYMINMAXQUEUE "EXFN_DESTROYMINMAXQUEUE"
    unsigned long _EXFN_GETSEGMENTINFO "EXFN_GETSEGMENTINFO"
    unsigned long _EXFN_CLEARERRORMINMAXQUEUE "EXFN_CLEARERRORMINMAXQUEUE"
    unsigned long _EXFN_CASCADESTREAM_CONFIG "EXFN_CASCADESTREAM_CONFIG"
    unsigned long _EXFN_CASCADESTREAM_RELEASE "EXFN_CASCADESTREAM_RELEASE"
    unsigned long _EXFN_CASCADESTREAM_GETCHANNELDATA "EXFN_CASCADESTREAM_GETCHANNELDATA"
    unsigned long _EXFN_CASCADESTREAM_CHANNELSDATAREAD "EXFN_CASCADESTREAM_CHANNELSDATAREAD"
    unsigned long _EXFN_RAWMULREC_TRANSFER "EXFN_RAWMULREC_TRANSFER"
    unsigned long _EXFX_DISK_STREAM_MASK "EXFX_DISK_STREAM_MASK"         
    unsigned long _EXFN_DISK_STREAM_INITIALIZE "EXFN_DISK_STREAM_INITIALIZE"
    unsigned long _EXFN_DISK_STREAM_START "EXFN_DISK_STREAM_START"
    unsigned long _EXFN_DISK_STREAM_STATUS "EXFN_DISK_STREAM_STATUS"
    unsigned long _EXFN_DISK_STREAM_STOP "EXFN_DISK_STREAM_STOP"
    unsigned long _EXFN_DISK_STREAM_CLOSE "EXFN_DISK_STREAM_CLOSE"
    unsigned long _EXFN_DISK_STREAM_WRITE_COUNT "EXFN_DISK_STREAM_WRITE_COUNT"
    unsigned long _EXFN_DISK_STREAM_ACQ_COUNT "EXFN_DISK_STREAM_ACQ_COUNT"
    unsigned long _EXFN_DISK_STREAM_ERRORS "EXFN_DISK_STREAM_ERRORS"
    unsigned long _EXFN_DISK_STREAM_TIMING_FLAG "EXFN_DISK_STREAM_TIMING_FLAG"
    unsigned long _EXFN_DISK_STREAM_TIMING_STATS "EXFN_DISK_STREAM_TIMING_STATS"
    unsigned long _EXFN_STREAM_INIT "EXFN_STREAM_INIT"
    unsigned long _EXFN_STREAM_CLEANUP "EXFN_STREAM_CLEANUP"
    unsigned long _EXFN_STREAM_START "EXFN_STREAM_START"
    unsigned long _EXFN_STREAM_GETSTATUS "EXFN_STREAM_GETSTATUS"
    unsigned long _EXFN_STREAM_ABORT "EXFN_STREAM_ABORT"
    unsigned long _EXFN_STREAM_TEST1 "EXFN_STREAM_TEST1"
    unsigned long _EXFN_STREAM_TEST2 "EXFN_STREAM_TEST2"
    unsigned long _STM_TRANSFER_ERROR_FIFOFULL "STM_TRANSFER_ERROR_FIFOFULL"

CS_MODE_SINGLE = _CS_MODE_SINGLE
CS_MODE_DUAL = _CS_MODE_DUAL
CS_MODE_QUAD = _CS_MODE_QUAD
CS_MODE_OCT = _CS_MODE_OCT
CS_MASKED_MODE = _CS_MASKED_MODE
CS_MODE_EXPERT_HISTOGRAM = _CS_MODE_EXPERT_HISTOGRAM
CS_MODE_SINGLE_CHANNEL2 = _CS_MODE_SINGLE_CHANNEL2
CS_MODE_POWER_ON = _CS_MODE_POWER_ON
CS_MODE_REFERENCE_CLK = _CS_MODE_REFERENCE_CLK
TIMESTAMP_GCLK = _TIMESTAMP_GCLK
TIMESTAMP_MCLK = _TIMESTAMP_MCLK
TIMESTAMP_SEG_RESET = _TIMESTAMP_SEG_RESET
TIMESTAMP_FREERUN = _TIMESTAMP_FREERUN
TIMESTAMP_DEFAULT = _TIMESTAMP_DEFAULT
TxMODE_SLAVE = _TxMODE_SLAVE
TxMODE_DATA_ANALOGONLY = _TxMODE_DATA_ANALOGONLY
TxMODE_DATA_FLOAT = _TxMODE_DATA_FLOAT
TxMODE_TIMESTAMP = _TxMODE_TIMESTAMP
TxMODE_DATA_16 = _TxMODE_DATA_16
TxMODE_DATA_ONLYDIGITAL = _TxMODE_DATA_ONLYDIGITAL
TxMODE_DATA_32 = _TxMODE_DATA_32
TxMODE_DATA_FFT = _TxMODE_DATA_FFT
TxMODE_DATA_INTERLEAVED = _TxMODE_DATA_INTERLEAVED
TxMODE_SEGMENT_TAIL = _TxMODE_SEGMENT_TAIL
TxMODE_HISTOGRAM = _TxMODE_HISTOGRAM
TxMODE_DATA_64 = _TxMODE_DATA_64
CS_CHAN_1 = _CS_CHAN_1
CS_CHAN_2 = _CS_CHAN_2
CS_FILTER_OFF = _CS_FILTER_OFF
CS_FILTER_ON = _CS_FILTER_ON
CS_COUPLING_DC = _CS_COUPLING_DC
CS_COUPLING_AC = _CS_COUPLING_AC
CS_COUPLING_MASK = _CS_COUPLING_MASK
CS_DIFFERENTIAL_INPUT = _CS_DIFFERENTIAL_INPUT
CS_DIRECT_ADC_INPUT = _CS_DIRECT_ADC_INPUT
CS_REAL_IMP_1M_OHM = _CS_REAL_IMP_1M_OHM
CS_REAL_IMP_50_OHM = _CS_REAL_IMP_50_OHM
CS_REAL_IMP_1K_OHM = _CS_REAL_IMP_1K_OHM
CS_GAIN_100_V = _CS_GAIN_100_V
CS_GAIN_40_V = _CS_GAIN_40_V
CS_GAIN_20_V = _CS_GAIN_20_V
CS_GAIN_10_V = _CS_GAIN_10_V
CS_GAIN_5_V = _CS_GAIN_5_V
CS_GAIN_8_V = _CS_GAIN_8_V
CS_GAIN_4_V = _CS_GAIN_4_V
CS_GAIN_3_V = _CS_GAIN_3_V
CS_GAIN_2_V = _CS_GAIN_2_V
CS_GAIN_1_V = _CS_GAIN_1_V
CS_GAIN_800_MV = _CS_GAIN_800_MV
CS_GAIN_500_MV = _CS_GAIN_500_MV
CS_GAIN_400_MV = _CS_GAIN_400_MV
CS_GAIN_200_MV = _CS_GAIN_200_MV
CS_GAIN_100_MV = _CS_GAIN_100_MV
CS_GAIN_50_MV = _CS_GAIN_50_MV
CS_TRIG_COND_NEG_SLOPE = _CS_TRIG_COND_NEG_SLOPE
CS_TRIG_COND_POS_SLOPE = _CS_TRIG_COND_POS_SLOPE
CS_TRIG_COND_PULSE_WIDTH = _CS_TRIG_COND_PULSE_WIDTH
CS_MAX_TRIG_COND = _CS_MAX_TRIG_COND
CS_RELATION_OR = _CS_RELATION_OR
CS_RELATION_AND = _CS_RELATION_AND
CS_TRIG_ENGINES_DIS = _CS_TRIG_ENGINES_DIS
CS_TRIG_ENGINES_EN = _CS_TRIG_ENGINES_EN
CS_TRIG_SOURCE_DISABLE = _CS_TRIG_SOURCE_DISABLE
CS_TRIG_SOURCE_CHAN_1 = _CS_TRIG_SOURCE_CHAN_1
CS_TRIG_SOURCE_CHAN_2 = _CS_TRIG_SOURCE_CHAN_2
CS_TRIG_SOURCE_EXT = _CS_TRIG_SOURCE_EXT
CS_BOARD_INFO = _CS_BOARD_INFO
CS_SYSTEM = _CS_SYSTEM
CS_CHANNEL = _CS_CHANNEL
CS_TRIGGER = _CS_TRIGGER
CS_ACQUISITION = _CS_ACQUISITION
CS_PARAMS = _CS_PARAMS
CS_FIR_CONFIG = _CS_FIR_CONFIG
CS_EXTENDED_BOARD_OPTIONS = _CS_EXTENDED_BOARD_OPTIONS
CS_TIMESTAMP_TICKFREQUENCY = _CS_TIMESTAMP_TICKFREQUENCY
CS_CHANNEL_ARRAY = _CS_CHANNEL_ARRAY
CS_TRIGGER_ARRAY = _CS_TRIGGER_ARRAY
CS_SMT_ENVELOPE_CONFIG = _CS_SMT_ENVELOPE_CONFIG
CS_SMT_HISTOGRAM_CONFIG = _CS_SMT_HISTOGRAM_CONFIG
CS_FFT_CONFIG = _CS_FFT_CONFIG
CS_FFTWINDOW_CONFIG = _CS_FFTWINDOW_CONFIG
CS_MULREC_AVG_COUNT = _CS_MULREC_AVG_COUNT
CS_TRIG_OUT_CFG = _CS_TRIG_OUT_CFG
CS_GET_SEGMENT_COUNT = _CS_GET_SEGMENT_COUNT
CS_TRIGGERED_INFO = _CS_TRIGGERED_INFO
CS_SEGMENTTAIL_SIZE_BYTES = _CS_SEGMENTTAIL_SIZE_BYTES
CS_STREAM_SEGMENTDATA_SIZE_SAMPLES = _CS_STREAM_SEGMENTDATA_SIZE_SAMPLES
CS_STREAM_TOTALDATA_SIZE_BYTES = _CS_STREAM_TOTALDATA_SIZE_BYTES
CS_IDENTIFY_LED = _CS_IDENTIFY_LED
CS_CAPTURE_MODE = _CS_CAPTURE_MODE
CS_DATAPACKING_MODE = _CS_DATAPACKING_MODE
CS_GET_DATAFORMAT_INFO = _CS_GET_DATAFORMAT_INFO
CS_CURRENT_CONFIGURATION = _CS_CURRENT_CONFIGURATION
CS_ACQUISITION_CONFIGURATION = _CS_ACQUISITION_CONFIGURATION
CS_ACQUIRED_CONFIGURATION = _CS_ACQUIRED_CONFIGURATION
ACTION_COMMIT = _ACTION_COMMIT
ACTION_START = _ACTION_START
ACTION_FORCE = _ACTION_FORCE
ACTION_ABORT = _ACTION_ABORT
ACTION_CALIB = _ACTION_CALIB
ACTION_RESET = _ACTION_RESET
ACTION_COMMIT_COERCE = _ACTION_COMMIT_COERCE
ACTION_TIMESTAMP_RESET = _ACTION_TIMESTAMP_RESET
ACTION_HISTOGRAM_RESET = _ACTION_HISTOGRAM_RESET
ACTION_ENCODER1_COUNT_RESET = _ACTION_ENCODER1_COUNT_RESET
ACTION_ENCODER2_COUNT_RESET = _ACTION_ENCODER2_COUNT_RESET
ACTION_HARD_RESET = _ACTION_HARD_RESET
ACQ_STATUS_READY = _ACQ_STATUS_READY
ACQ_STATUS_WAIT_TRIGGER = _ACQ_STATUS_WAIT_TRIGGER
ACQ_STATUS_TRIGGERED = _ACQ_STATUS_TRIGGERED
ACQ_STATUS_BUSY_TX = _ACQ_STATUS_BUSY_TX
ACQ_STATUS_BUSY_CALIB = _ACQ_STATUS_BUSY_CALIB
CSDEMO8_BOARDTYPE = _CSDEMO8_BOARDTYPE
CSDEMO12_BOARDTYPE = _CSDEMO12_BOARDTYPE
CSDEMO14_BOARDTYPE = _CSDEMO14_BOARDTYPE
CSDEMO16_BOARDTYPE = _CSDEMO16_BOARDTYPE
CSDEMO32_BOARDTYPE = _CSDEMO32_BOARDTYPE
CSDEMO_BT_MASK = _CSDEMO_BT_MASK
CSDEMO_BT_FIRST_BOARD = _CSDEMO_BT_FIRST_BOARD
CSDEMO_BT_LAST_BOARD = _CSDEMO_BT_LAST_BOARD
CSPCIEx_BOARDTYPE = _CSPCIEx_BOARDTYPE
CSNUCLEONBASE_BOARDTYPE = _CSNUCLEONBASE_BOARDTYPE
CS16x1_BOARDTYPE = _CS16x1_BOARDTYPE
CS16x2_BOARDTYPE = _CS16x2_BOARDTYPE
CS14x1_BOARDTYPE = _CS14x1_BOARDTYPE
CS14x2_BOARDTYPE = _CS14x2_BOARDTYPE
CS12x1_BOARDTYPE = _CS12x1_BOARDTYPE
CS12x2_BOARDTYPE = _CS12x2_BOARDTYPE
CS16xyy_BT_FIRST_BOARD = _CS16xyy_BT_FIRST_BOARD
CS16xyy_LAST_BOARD = _CS16xyy_LAST_BOARD
CS16xyy_BASEBOARD = _CS16xyy_BASEBOARD
CSE42x0_BOARDTYPE = _CSE42x0_BOARDTYPE
CSE42x2_BOARDTYPE = _CSE42x2_BOARDTYPE
CSE42x4_BOARDTYPE = _CSE42x4_BOARDTYPE
CSE42x7_BOARDTYPE = _CSE42x7_BOARDTYPE
CSE43x0_BOARDTYPE = _CSE43x0_BOARDTYPE
CSE43x2_BOARDTYPE = _CSE43x2_BOARDTYPE
CSE43x4_BOARDTYPE = _CSE43x4_BOARDTYPE
CSE43x7_BOARDTYPE = _CSE43x7_BOARDTYPE
CSE44x0_BOARDTYPE = _CSE44x0_BOARDTYPE
CSE44x2_BOARDTYPE = _CSE44x2_BOARDTYPE
CSE44x4_BOARDTYPE = _CSE44x4_BOARDTYPE
CSE44x7_BOARDTYPE = _CSE44x7_BOARDTYPE
CSE4abc_FIRST_BOARD = _CSE4abc_FIRST_BOARD
CSE4abc_LAST_BOARD = _CSE4abc_LAST_BOARD
CSE4abc_BASEBOARD = _CSE4abc_BASEBOARD
CS8220_BOARDTYPE = _CS8220_BOARDTYPE
CS8221_BOARDTYPE = _CS8221_BOARDTYPE
CS8222_BOARDTYPE = _CS8222_BOARDTYPE
CS8223_BOARDTYPE = _CS8223_BOARDTYPE
CS8224_BOARDTYPE = _CS8224_BOARDTYPE
CS8225_BOARDTYPE = _CS8225_BOARDTYPE
CS8226_BOARDTYPE = _CS8226_BOARDTYPE
CS8227_BOARDTYPE = _CS8227_BOARDTYPE
CS8228_BOARDTYPE = _CS8228_BOARDTYPE
CS8229_BOARDTYPE = _CS8229_BOARDTYPE
CS822x_BOARDTYPE_MASK = _CS822x_BOARDTYPE_MASK
CS8240_BOARDTYPE = _CS8240_BOARDTYPE
CS8241_BOARDTYPE = _CS8241_BOARDTYPE
CS8242_BOARDTYPE = _CS8242_BOARDTYPE
CS8243_BOARDTYPE = _CS8243_BOARDTYPE
CS8244_BOARDTYPE = _CS8244_BOARDTYPE
CS8245_BOARDTYPE = _CS8245_BOARDTYPE
CS8246_BOARDTYPE = _CS8246_BOARDTYPE
CS8247_BOARDTYPE = _CS8247_BOARDTYPE
CS8248_BOARDTYPE = _CS8248_BOARDTYPE
CS8249_BOARDTYPE = _CS8249_BOARDTYPE
CS824x_BOARDTYPE_MASK = _CS824x_BOARDTYPE_MASK
CS8280_BOARDTYPE = _CS8280_BOARDTYPE
CS8281_BOARDTYPE = _CS8281_BOARDTYPE
CS8282_BOARDTYPE = _CS8282_BOARDTYPE
CS8283_BOARDTYPE = _CS8283_BOARDTYPE
CS8284_BOARDTYPE = _CS8284_BOARDTYPE
CS8285_BOARDTYPE = _CS8285_BOARDTYPE
CS8286_BOARDTYPE = _CS8286_BOARDTYPE
CS8287_BOARDTYPE = _CS8287_BOARDTYPE
CS8288_BOARDTYPE = _CS8288_BOARDTYPE
CS8289_BOARDTYPE = _CS8289_BOARDTYPE
CS828x_BOARDTYPE_MASK = _CS828x_BOARDTYPE_MASK
CS8320_BOARDTYPE = _CS8320_BOARDTYPE
CS8321_BOARDTYPE = _CS8321_BOARDTYPE
CS8322_BOARDTYPE = _CS8322_BOARDTYPE
CS8323_BOARDTYPE = _CS8323_BOARDTYPE
CS8324_BOARDTYPE = _CS8324_BOARDTYPE
CS8325_BOARDTYPE = _CS8325_BOARDTYPE
CS8326_BOARDTYPE = _CS8326_BOARDTYPE
CS8327_BOARDTYPE = _CS8327_BOARDTYPE
CS8328_BOARDTYPE = _CS8328_BOARDTYPE
CS8329_BOARDTYPE = _CS8329_BOARDTYPE
CS832x_BOARDTYPE_MASK = _CS832x_BOARDTYPE_MASK
CS8340_BOARDTYPE = _CS8340_BOARDTYPE
CS8341_BOARDTYPE = _CS8341_BOARDTYPE
CS8342_BOARDTYPE = _CS8342_BOARDTYPE
CS8343_BOARDTYPE = _CS8343_BOARDTYPE
CS8344_BOARDTYPE = _CS8344_BOARDTYPE
CS8345_BOARDTYPE = _CS8345_BOARDTYPE
CS8346_BOARDTYPE = _CS8346_BOARDTYPE
CS8347_BOARDTYPE = _CS8347_BOARDTYPE
CS8348_BOARDTYPE = _CS8348_BOARDTYPE
CS8349_BOARDTYPE = _CS8349_BOARDTYPE
CS834x_BOARDTYPE_MASK = _CS834x_BOARDTYPE_MASK
CS8380_BOARDTYPE = _CS8380_BOARDTYPE
CS8381_BOARDTYPE = _CS8381_BOARDTYPE
CS8382_BOARDTYPE = _CS8382_BOARDTYPE
CS8383_BOARDTYPE = _CS8383_BOARDTYPE
CS8384_BOARDTYPE = _CS8384_BOARDTYPE
CS8385_BOARDTYPE = _CS8385_BOARDTYPE
CS8386_BOARDTYPE = _CS8386_BOARDTYPE
CS8387_BOARDTYPE = _CS8387_BOARDTYPE
CS8388_BOARDTYPE = _CS8388_BOARDTYPE
CS8389_BOARDTYPE = _CS8389_BOARDTYPE
CS838x_BOARDTYPE_MASK = _CS838x_BOARDTYPE_MASK
CS8210_BOARDTYPE = _CS8210_BOARDTYPE
CS8211_BOARDTYPE = _CS8211_BOARDTYPE
CS8212_BOARDTYPE = _CS8212_BOARDTYPE
CS8213_BOARDTYPE = _CS8213_BOARDTYPE
CS8214_BOARDTYPE = _CS8214_BOARDTYPE
CS8215_BOARDTYPE = _CS8215_BOARDTYPE
CS8216_BOARDTYPE = _CS8216_BOARDTYPE
CS8217_BOARDTYPE = _CS8217_BOARDTYPE
CS8218_BOARDTYPE = _CS8218_BOARDTYPE
CS8219_BOARDTYPE = _CS8219_BOARDTYPE
CS821x_BOARDTYPE_MASK = _CS821x_BOARDTYPE_MASK
CS8310_BOARDTYPE = _CS8310_BOARDTYPE
CS8311_BOARDTYPE = _CS8311_BOARDTYPE
CS8312_BOARDTYPE = _CS8312_BOARDTYPE
CS8313_BOARDTYPE = _CS8313_BOARDTYPE
CS8314_BOARDTYPE = _CS8314_BOARDTYPE
CS8315_BOARDTYPE = _CS8315_BOARDTYPE
CS8316_BOARDTYPE = _CS8316_BOARDTYPE
CS8317_BOARDTYPE = _CS8317_BOARDTYPE
CS8318_BOARDTYPE = _CS8318_BOARDTYPE
CS8319_BOARDTYPE = _CS8319_BOARDTYPE
CS831x_BOARDTYPE_MASK = _CS831x_BOARDTYPE_MASK
CS8410_BOARDTYPE = _CS8410_BOARDTYPE
CS8412_BOARDTYPE = _CS8412_BOARDTYPE
CS8420_BOARDTYPE = _CS8420_BOARDTYPE
CS8422_BOARDTYPE = _CS8422_BOARDTYPE
CS8440_BOARDTYPE = _CS8440_BOARDTYPE
CS8442_BOARDTYPE = _CS8442_BOARDTYPE
CS8480_BOARDTYPE = _CS8480_BOARDTYPE
CS8482_BOARDTYPE = _CS8482_BOARDTYPE
CS84xx_BOARDTYPE_MASK = _CS84xx_BOARDTYPE_MASK
CS8_BT_MASK = _CS8_BT_MASK
CS8_BT_FIRST_BOARD = _CS8_BT_FIRST_BOARD
CS8_BT_LAST_BOARD = _CS8_BT_LAST_BOARD
CS8xxx_BASEBOARD = _CS8xxx_BASEBOARD
CS_ZAP_FIRST_BOARD = _CS_ZAP_FIRST_BOARD
CS_ZAP_LAST_BOARD = _CS_ZAP_LAST_BOARD
CS_ZAP_BASEBOARD = _CS_ZAP_BASEBOARD
CS22G8_BOARDTYPE = _CS22G8_BOARDTYPE
CSxyG8_BOARDTYPE_MASK = _CSxyG8_BOARDTYPE_MASK
CS21G8_BOARDTYPE = _CS21G8_BOARDTYPE
CS11G8_BOARDTYPE = _CS11G8_BOARDTYPE
LAB11G_BOARDTYPE = _LAB11G_BOARDTYPE
CSxyG8_FIRST_BOARD = _CSxyG8_FIRST_BOARD
CSxyG8_LAST_BOARD = _CSxyG8_LAST_BOARD
CS_BASE8_BOARDTYPE = _CS_BASE8_BOARDTYPE
CS_COBRAX_BOARDTYPE_MASK = _CS_COBRAX_BOARDTYPE_MASK
CSX11G8_BOARDTYPE = _CSX11G8_BOARDTYPE
CSX21G8_BOARDTYPE = _CSX21G8_BOARDTYPE
CSX22G8_BOARDTYPE = _CSX22G8_BOARDTYPE
CSX13G8_BOARDTYPE = _CSX13G8_BOARDTYPE
CSX23G8_BOARDTYPE = _CSX23G8_BOARDTYPE
CSX14G8_BOARDTYPE = _CSX14G8_BOARDTYPE
CSX_NTS_BOARDTYPE = _CSX_NTS_BOARDTYPE
CSX24G8_BOARDTYPE = _CSX24G8_BOARDTYPE
CSEcdG8_FIRST_BOARD = _CSEcdG8_FIRST_BOARD
CSEcdG8_LAST_BOARD = _CSEcdG8_LAST_BOARD
CS12500_BOARDTYPE = _CS12500_BOARDTYPE
CS121G_BOARDTYPE = _CS121G_BOARDTYPE
CS122G_BOARDTYPE = _CS122G_BOARDTYPE
CS14250_BOARDTYPE = _CS14250_BOARDTYPE
CS14500_BOARDTYPE = _CS14500_BOARDTYPE
CS141G_BOARDTYPE = _CS141G_BOARDTYPE
CSJD_FIRST_BOARD = _CSJD_FIRST_BOARD
CSJD_LAST_BOARD = _CSJD_LAST_BOARD
CSUSB_BOARDTYPE = _CSUSB_BOARDTYPE
CSUSB_BT_FIRST_BOARD = _CSUSB_BT_FIRST_BOARD
CSUSB_BT_LAST_BOARD = _CSUSB_BT_LAST_BOARD
CSDECADE123G_BOARDTYPE = _CSDECADE123G_BOARDTYPE
CSDECADE126G_BOARDTYPE = _CSDECADE126G_BOARDTYPE
CSDECADE_FIRST_BOARD = _CSDECADE_FIRST_BOARD
CSDECADE_LAST_BOARD = _CSDECADE_LAST_BOARD
CSHEXAGON_161G4_BOARDTYPE = _CSHEXAGON_161G4_BOARDTYPE
CSHEXAGON_161G2_BOARDTYPE = _CSHEXAGON_161G2_BOARDTYPE
CSHEXAGON_16504_BOARDTYPE = _CSHEXAGON_16504_BOARDTYPE
CSHEXAGON_16502_BOARDTYPE = _CSHEXAGON_16502_BOARDTYPE
CSHEXAGON_FIRST_BOARD = _CSHEXAGON_FIRST_BOARD
CSHEXAGON_LAST_BOARD = _CSHEXAGON_LAST_BOARD
FCI_BOARDTYPE = _FCI_BOARDTYPE
CS_TIMEOUT_DISABLE = _CS_TIMEOUT_DISABLE
ACQ_EVENT_TRIGGERED = _ACQ_EVENT_TRIGGERED
ACQ_EVENT_END_BUSY = _ACQ_EVENT_END_BUSY
ACQ_EVENT_END_TXFER = _ACQ_EVENT_END_TXFER
ACQ_EVENT_ALARM = _ACQ_EVENT_ALARM
NUMBER_ACQ_EVENTS = _NUMBER_ACQ_EVENTS
CAPS_SAMPLE_RATES = _CAPS_SAMPLE_RATES
CAPS_INPUT_RANGES = _CAPS_INPUT_RANGES
CAPS_IMPEDANCES = _CAPS_IMPEDANCES
CAPS_COUPLINGS = _CAPS_COUPLINGS
CAPS_ACQ_MODES = _CAPS_ACQ_MODES
CAPS_TERMINATIONS = _CAPS_TERMINATIONS
CAPS_FLEXIBLE_TRIGGER = _CAPS_FLEXIBLE_TRIGGER
CAPS_BOARD_TRIGGER_ENGINES = _CAPS_BOARD_TRIGGER_ENGINES
CAPS_TRIGGER_SOURCES = _CAPS_TRIGGER_SOURCES
CAPS_FILTERS = _CAPS_FILTERS
CAPS_MAX_SEGMENT_PADDING = _CAPS_MAX_SEGMENT_PADDING
CAPS_DC_OFFSET_ADJUST = _CAPS_DC_OFFSET_ADJUST
CAPS_CLK_IN = _CAPS_CLK_IN
CAPS_BOOTIMAGE0 = _CAPS_BOOTIMAGE0
CAPS_AUX_CONFIG = _CAPS_AUX_CONFIG
CAPS_CLOCK_OUT = _CAPS_CLOCK_OUT
CAPS_TRIG_OUT = _CAPS_TRIG_OUT
CAPS_TRIG_ENABLE = _CAPS_TRIG_ENABLE
CAPS_AUX_OUT = _CAPS_AUX_OUT
CAPS_AUX_IN_TIMESTAMP = _CAPS_AUX_IN_TIMESTAMP
CAPS_FWCHANGE_REBOOT = _CAPS_FWCHANGE_REBOOT
CAPS_EXT_TRIGGER_UNIPOLAR = _CAPS_EXT_TRIGGER_UNIPOLAR
CAPS_TRIG_ENGINES_PER_CHAN = _CAPS_TRIG_ENGINES_PER_CHAN
CAPS_MULREC = _CAPS_MULREC
CAPS_TRIGGER_RES = _CAPS_TRIGGER_RES
CAPS_MIN_EXT_RATE = _CAPS_MIN_EXT_RATE
CAPS_SKIP_COUNT = _CAPS_SKIP_COUNT
CAPS_MAX_EXT_RATE = _CAPS_MAX_EXT_RATE
CAPS_TRANSFER_EX = _CAPS_TRANSFER_EX
CAPS_STM_TRANSFER_SIZE_BOUNDARY = _CAPS_STM_TRANSFER_SIZE_BOUNDARY
CAPS_STM_MAX_SEGMENTSIZE = _CAPS_STM_MAX_SEGMENTSIZE
CAPS_SINGLE_CHANNEL2 = _CAPS_SINGLE_CHANNEL2
CAPS_SELF_IDENTIFY = _CAPS_SELF_IDENTIFY
CAPS_MAX_PRE_TRIGGER = _CAPS_MAX_PRE_TRIGGER
CAPS_DEPTH_INCREMENT = _CAPS_DEPTH_INCREMENT
CAPS_TRIGGER_DELAY_INCREMENT = _CAPS_TRIGGER_DELAY_INCREMENT
CS_NO_FILTER = _CS_NO_FILTER
CS_NO_EXTTRIG = _CS_NO_EXTTRIG
CS_MODE_NO_DDC = _CS_MODE_NO_DDC
CS_DDC_MODE_ENABLE = _CS_DDC_MODE_ENABLE
CS_DDC_MODE_CH1 = _CS_DDC_MODE_CH1
CS_DDC_MODE_CH2 = _CS_DDC_MODE_CH2
CS_DDC_DEBUG_MUX = _CS_DDC_DEBUG_MUX
CS_DDC_DEBUG_NCO = _CS_DDC_DEBUG_NCO
CS_DDC_MODE_LAST = _CS_DDC_MODE_LAST
CS_DDC_MUX_ENABLE = _CS_DDC_MUX_ENABLE
CS_DDC_CORE_CONFIG = _CS_DDC_CORE_CONFIG
CS_DDC_FIR_COEF_CONFIG = _CS_DDC_FIR_COEF_CONFIG
CS_DDC_CFIR_COEF_CONFIG = _CS_DDC_CFIR_COEF_CONFIG
CS_DDC_PFIR_COEF_CONFIG = _CS_DDC_PFIR_COEF_CONFIG
CS_DDC_WRITE_FIFO_DATA = _CS_DDC_WRITE_FIFO_DATA
CS_DDC_READ_FIFO_DATA = _CS_DDC_READ_FIFO_DATA
SIZE_OF_FIR_COEFS = _SIZE_OF_FIR_COEFS
SIZE_OF_CFIR_COEFS = _SIZE_OF_CFIR_COEFS
SIZE_OF_PFIR_COEFS = _SIZE_OF_PFIR_COEFS
DDC_FILTER_COEFS_MAX_SIZE = _DDC_FILTER_COEFS_MAX_SIZE
DDC_CORE_CONFIG_OFFSET = _DDC_CORE_CONFIG_OFFSET
CS_DDC_CONFIG = _CS_DDC_CONFIG
CS_DDC_SEND_CMD = _CS_DDC_SEND_CMD
CS_DDC_SCALE_OVERFLOW_STATUS = _CS_DDC_SCALE_OVERFLOW_STATUS
CS_PE_ENABLE = _CS_PE_ENABLE
CS_PE_DISABLE = _CS_PE_DISABLE
CS_ENCODER1_COUNT_RESET = _CS_ENCODER1_COUNT_RESET
CS_ENCODER2_COUNT_RESET = _CS_ENCODER2_COUNT_RESET
CS_ENCODER1_CONFIG = _CS_ENCODER1_CONFIG
CS_ENCODER2_CONFIG = _CS_ENCODER2_CONFIG
CS_ENCODER1_COUNT = _CS_ENCODER1_COUNT
CS_ENCODER2_COUNT = _CS_ENCODER2_COUNT
CS_PE_INPUT_TYPE_STEPANDDIRECTION = _CS_PE_INPUT_TYPE_STEPANDDIRECTION
CS_PE_INPUT_TYPE_QUADRATURE = _CS_PE_INPUT_TYPE_QUADRATURE
CS_PE_ENCODER_MODE_STAMP = _CS_PE_ENCODER_MODE_STAMP
CS_PE_ENCODER_MODE_TOP = _CS_PE_ENCODER_MODE_TOP
CS_OCT_ENABLE = _CS_OCT_ENABLE
CS_OCT_DISABLE = _CS_OCT_DISABLE
CS_OCT_MODE0 = _CS_OCT_MODE0
CS_OCT_MODE1 = _CS_OCT_MODE1
CS_OCT_CORE_CONFIG = _CS_OCT_CORE_CONFIG
CS_OCT_RECORD_LEN = _CS_OCT_RECORD_LEN
CS_OCT_CMD_MODE = _CS_OCT_CMD_MODE
CS_MODE_USER1 = _CS_MODE_USER1
CS_MODE_USER2 = _CS_MODE_USER2
CS_MODE_SW_AVERAGING = _CS_MODE_SW_AVERAGING
CS_BBOPTIONS_FIR = _CS_BBOPTIONS_FIR
CS_BBOPTIONS_AVERAGING = _CS_BBOPTIONS_AVERAGING
CS_BBOPTIONS_MINMAXDETECT = _CS_BBOPTIONS_MINMAXDETECT
CS_BBOPTIONS_CASCADESTREAM = _CS_BBOPTIONS_CASCADESTREAM
CS_BBOPTIONS_MULREC_AVG = _CS_BBOPTIONS_MULREC_AVG
CS_BBOPTIONS_SMT = _CS_BBOPTIONS_SMT
CS_BBOPTIONS_FFT_8K = _CS_BBOPTIONS_FFT_8K
CS_BBOPTIONS_FFT_4K = _CS_BBOPTIONS_FFT_4K
CS_BBOPTIONS_MULREC_AVG_TD = _CS_BBOPTIONS_MULREC_AVG_TD
CS_BBOPTIONS_DDC = _CS_BBOPTIONS_DDC
CS_BBOPTIONS_OCT = _CS_BBOPTIONS_OCT
CS_BBOPTIONS_STREAM = _CS_BBOPTIONS_STREAM
CS_AOPTIONS_HISTOGRAM = _CS_AOPTIONS_HISTOGRAM
CS_BBOPTIONS_FFTMASK = _CS_BBOPTIONS_FFTMASK
CS_BBOPTIONS_EXPERT_MASK = _CS_BBOPTIONS_EXPERT_MASK
CSMV_BBOPTIONS_BIG_TRIGGER = _CSMV_BBOPTIONS_BIG_TRIGGER
MAX_HW_AVERAGING_DEPTH = _MAX_HW_AVERAGING_DEPTH
MAX_HW_AVERAGE_SEGMENTCOUNT = _MAX_HW_AVERAGE_SEGMENTCOUNT
MAX_SW_AVERAGING_SEGMENTSIZE = _MAX_SW_AVERAGING_SEGMENTSIZE
MAX_SW_AVERAGE_SEGMENTCOUNT = _MAX_SW_AVERAGE_SEGMENTCOUNT
MAX_MINMAXDETECT_SEGMENTSIZE = _MAX_MINMAXDETECT_SEGMENTSIZE
MAX_MINMAXDETECT_SEGMENTCOUNT = _MAX_MINMAXDETECT_SEGMENTCOUNT
MAX_DISKSTREAM_CHANNELS = _MAX_DISKSTREAM_CHANNELS
EXFN_CREATEMINMAXQUEUE = _EXFN_CREATEMINMAXQUEUE
EXFN_DESTROYMINMAXQUEUE = _EXFN_DESTROYMINMAXQUEUE
EXFN_GETSEGMENTINFO = _EXFN_GETSEGMENTINFO
EXFN_CLEARERRORMINMAXQUEUE = _EXFN_CLEARERRORMINMAXQUEUE
EXFN_CASCADESTREAM_CONFIG = _EXFN_CASCADESTREAM_CONFIG
EXFN_CASCADESTREAM_RELEASE = _EXFN_CASCADESTREAM_RELEASE
EXFN_CASCADESTREAM_GETCHANNELDATA = _EXFN_CASCADESTREAM_GETCHANNELDATA
EXFN_CASCADESTREAM_CHANNELSDATAREAD = _EXFN_CASCADESTREAM_CHANNELSDATAREAD
EXFN_RAWMULREC_TRANSFER = _EXFN_RAWMULREC_TRANSFER
EXFX_DISK_STREAM_MASK = _EXFX_DISK_STREAM_MASK
EXFN_DISK_STREAM_INITIALIZE = _EXFN_DISK_STREAM_INITIALIZE
EXFN_DISK_STREAM_START = _EXFN_DISK_STREAM_START
EXFN_DISK_STREAM_STATUS = _EXFN_DISK_STREAM_STATUS
EXFN_DISK_STREAM_STOP = _EXFN_DISK_STREAM_STOP
EXFN_DISK_STREAM_CLOSE = _EXFN_DISK_STREAM_CLOSE
EXFN_DISK_STREAM_WRITE_COUNT = _EXFN_DISK_STREAM_WRITE_COUNT
EXFN_DISK_STREAM_ACQ_COUNT = _EXFN_DISK_STREAM_ACQ_COUNT
EXFN_DISK_STREAM_ERRORS = _EXFN_DISK_STREAM_ERRORS
EXFN_DISK_STREAM_TIMING_FLAG = _EXFN_DISK_STREAM_TIMING_FLAG
EXFN_DISK_STREAM_TIMING_STATS = _EXFN_DISK_STREAM_TIMING_STATS
EXFN_STREAM_INIT = _EXFN_STREAM_INIT
EXFN_STREAM_CLEANUP = _EXFN_STREAM_CLEANUP
EXFN_STREAM_START = _EXFN_STREAM_START
EXFN_STREAM_GETSTATUS = _EXFN_STREAM_GETSTATUS
EXFN_STREAM_ABORT = _EXFN_STREAM_ABORT
EXFN_STREAM_TEST1 = _EXFN_STREAM_TEST1
EXFN_STREAM_TEST2 = _EXFN_STREAM_TEST2
STM_TRANSFER_ERROR_FIFOFULL = _STM_TRANSFER_ERROR_FIFOFULL